---
sidebar: sidebar
permalink: analyze-error-logs.html
keywords: analyze error logs, errors, error severity, Microsoft SQL Server error logs, smart analysis, Agentic AI
summary: "Analyze error logs within Workload Factory for Databases."
---
= Analyze error logs in Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Use the Smart error log analyzer to automatically interpret Microsoft SQL Server error logs so that you can quickly identify and resolve issues. The Agentic AI-based analysis requires Amazon Bedrock integration.

.About this task
Error log analysis and remediation help maintain the health and performance of SQL Server instances. Interpreting SQL Server error logs effectively requires careful analysis and expertise. Manual monitoring, error detection, and root cause analysis are time-intensive and prone to errors. These challenges can delay issue resolution, increased downtime, and operational inefficiencies. The Smart error log analyzer addresses these challenges with these key benefits:

* Smart grouping: Intelligently consolidates errors by uniqueness, severity, and category, and simplifies the troubleshooting process for faster, more effective resolutions.
* AI-driven investigation: Leverages AI to proactively analyze errors, providing clear, actionable insights to accelerate issue identification without requiring deep expertise.
* Error enrichment: Enhances error logs with external references, offering contextual clarity to improve understanding and decision-making.
* Best-practice remediation: Delivers tailored, remediation recommendations for SQL Server workloads running on FSx for ONTAP, empowering users of all skill levels to resolve issues confidently.

Whenever you use the error log analyzer, you maintain full control over your environment while benefiting from advanced AI analysis.

To use the error log analyzer, you need to activate Amazon Bedrock, select the model Workload Factory uses, create a private endpoint to connect to Amazon Bedrock, add permissions, and create an enterprise license. 

link:https://aws.amazon.com/bedrock/pricing/[Amazon Bedrock pricing^]

.Before you begin
To use the error log analyzer, you must meet the following prerequisites:

* You must have link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[AWS account credentials and _read/write_ mode permissions^] to create a new database host in Workload Factory. 
* link:https://docs.netapp.com/us-en/workload-databases/register-instance.html[Register a SQL Server instance^] in Workload Factory.
* 

.Steps

. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Databases tile, select *Go to Databases inventory*.
. In Databases, select the *Inventory* tab. 
. Select *Microsoft SQL Server* as the database engine type. 
. From the Instances tab, locate the specific SQL Server instance you want to analyze and then select *Investigate errors* from the menu.
. From the *Error investigation* tab, complete the following prerequisites as described in the console: 
+
* Amazon Bedrock
* Networking: Private endpoint for Amazon Bedrock
* Permissions for EC2 instance profile role
* Credentials associated with Workload Database Management (wlmdb)
. When prerequisites are met, select *Investigate now* to use the error log analyzer to gain insights into your SQL Server error logs.
+
After the scan, errors are displayed in the console, providing a comprehensive view of the issues detected by the Smart error log analyzer.
. Use filters to refine the displayed errors based on criteria such as severity, time frame, and error code.
. Review the detailed error information, including original error message, AI-based explanation, and suggested remediation steps to resolve the errors.

