---
sidebar: sidebar
permalink: connect-clone-cicd.html
keywords: connect ci/cd pipeline, clone 
summary: Connect a sandbox clone to a CI/CD pipeline with REST API code to improve software delivery via automation. 
---
= Connect a sandbox clone to CI/CD tools
:icons: font
:imagesdir: ./media/

[.lead]
Connect a sandbox clone to a continuous integration and continuous delivery (CI/CD) pipeline with REST API code to improve software delivery via automation. 

.About this task 
To deliver a new version of software automatically to your database clone, you should connect to a CI/CD pipeline. Use the REST API code provided from this operation to make the connection. 

.Steps 
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^]. 
. In the Databases tile, select *Go to Databases Inventory*. 
. In Databases, select the *Sandboxes* tab.
. In the Sandboxes tab, click the three dots menu of the sandbox clone to connect to CI/CD tools.
. Select *Connect to CI/CD tools*. 
. In the CI/CD dialog, copy or download the REST API code needed to connect to CI/CD tools. 
. Click *Close*. 
