---
sidebar: sidebar
permalink: create-sandbox-clone.html
keywords: create, clone, sandbox
summary: Create a sandbox clone in Workload Factory for Databases. 
---
= Create a sandbox clone in Workload Factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Creating a sandbox clone of a database in Workload Factory for Databases lets you use the clone for development, testing, integration, analytics, training, QA, and more without altering the source database. 

.About this task
A sandbox clone is created from the most recent snapshot on the source database. It may be cloned in the same Microsoft SQL Server as the source database or cloned in another Microsoft SQL Server as long as they share the same FSx for ONTAP file system. 

.Before you begin
Ensure you complete the following prerequisites before you create a sandbox clone.

Credentials and permissions::: You must have link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[AWS account credentials and _read_ or _automate_ mode permissions^] to create a sandbox clone in Workload Factory. 
+
Alternatively, you can use the Codebox to copy a partially completed template or create a completed template so that you can create the sandbox clone outside of Workload Factory using REST API. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html[Learn more about Codebox automation^].

Microsoft SQL Server::: You must have a managed Microsoft SQL Server in Workload Factory for Databases to host the new sandbox clone.

AWS Systems Manager::: Ensure the `NT Authority\SYSTEM` user privilege is enabled in the Microsoft SQL host via AWS Systems Manager. 

Source database::: You need a source database available for the clone. 

.Steps
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].
. In the Databases tile, select *Go to Databases Inventory*.
. In Databases, select the *Sandboxes* tab. 
. In the Sandboxes tab, select *Create new sandbox*.
. On the Create new sandbox page, under Database source, provide the following: 
.. *Source database host*: Select the source database host. 
.. *Source database instance*: Select the source database instance.
.. *Source database*: Select the source database to clone from.
. Under Database target, provide the following: 
.. *Target database host*: Select a target database host for the sandbox clone that is in the same VPC and has the same FSx for ONTAP file system as the source host. 
.. *Target database instance*: Select the target database instance for the sandbox clone. 
.. *Target database*: Enter a name for the sandbox clone. 
. *Mount*: When cloning a SQL database that has multiple data and/or log files, Workload Factory clones all files under the auto-assigned or defined drive letter. 
+
Select one of the following options: 
+
.. *Auto-assign mount point* 
.. *Define mount point path* 
+
Provide the following to define the mount point path: 
+
** Enter the drive letter for the data file path.
** Enter the drive letter for the log file path. 
. *Define tag*: Select a tag to define the sandbox clone.
. Click *Create*. 

To check the job's progress, go to the *Job monitoring* tab. 