---
sidebar: sidebar
permalink: create-database.html
keywords: create, database, creation, Microsoft SQL
summary: Create a Microsoft SQL database with Workload Factory Databases. 
---
= Create a Microsoft SQL database in Workload Factory Databases
:icons: font
:imagesdir: ./media/

[.lead]
Create a Microsoft SQL database in Workload Factory Databases with automate permissions. 

== About this task
Creating a new Microsoft SQL database in the Workload Factory console makes it possible for you to manage the resource within Workload Factory. 

Upon creation, two new volumes are created in the FSx for ONTAP file system consisting of independent LUNs to host data and log files for the database. The database files in the new database are thin-provisioned and consume only a few MBs of the total size allocated for the new database. 

If you want to segregate storage for the database, you can do this by using a virtual mount point. The virtual mount point lets you consolidate databases to a few common drives on the host. 

You can create a database in Workload Factory or copy or download a code template to complete the operation outside Workload Factory. Review the Workload Factory operational modes to decide which mode you'd like to use. 

NOTE: Microsoft SQL servers using SMB protocol don't support database creation. 

=== Workload Factory operational modes
Workload Factory offers three operational modes depending on how comfortable you are with letting Workload Factory manage your AWS resources. 

*_Basic_ mode*: in this mode of operation, you don't need to associate any AWS account credentials in Workload Factory. You can copy or download an empty template from the Codebox to be completed outside Workload Factory. 

*_Read_ mode*: in this mode of operation, you provide AWS account credentials with read permissions which lets you complete the _Quick create_ or _Advanced create_ form and then copy or download it. 

*_Automate_ mode*: in this mode of operation, you provide AWS account credentials with automate permissions which lets you create and manage AWS resources within Workload Factory. 

In _Basic_ mode, you'll copy or download the empty template from the Codebox. In _Read_ mode, you can complete the _Quick create_ or _Advanced create_ form and then copy or download it. Depending on your level of trust, you can create the new server within Workload Factory with _automate_ permissions, download a completed YAML template with _read_ permissions, or download an empty YAML template in _basic_ mode. 

== Before you begin
Ensure you have the following prerequisites before you create a new database host. 

Credentials and permissions::: You must have link:https://docs.netapp.com/us-en/workload-setup-admin/manage-credentials.html[AWS account credentials and automate mode permissions^] to create a new database host in Workload Factory. 
+
Alternatively, you can use the Codebox to copy an empty template or create a completed template so that you can deploy a database outside of Workload Factory using REST API, AWS CLI, or AWS CloudFormation. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html[Learn more about Codebox automation^].

Windows host::: You must have enough drive letters available on the Microsoft SQL server to create new drives for the new database. 

Microsoft SQL server::: You must have a managed Microsoft SQL server in Workload Factory for Databases to host the new database. 

.Steps
You can use _Quick create_ or _Advanced create_ deployment modes to complete this task in Workload Factory with _Automate_ mode permissions.

[role="tabbed-block"]
====

.Quick create
-- 
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Select the *Managed hosts* tab. 
. Click the three dots menu of the managed host you'd like to create a database in. 
. Select *Create user database*.
. On the Create user database page, under Database information, provide the following: 
.. *Database name*: Enter name for the database. 
.. *Collation*: Select a collation for the database. The default collation SQL_Latin1_General_CP1_CI_AS" on Microsoft SQL server is selected. 
. Under File settings, provide the following: 
.. *File settings mode*: Select *Quick create*. 
.. *File names & path*:
... *Data file name*: Enter the data file name.
... *Log file name*: Enter the log file name. 
.. *File sizes*: Enter the data size and log size for the database. 
. Click *Create*. 
--

.Advanced create
--
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Select the *Managed hosts* tab. 
. Click the three dots menu of the managed host you'd like to create a database in. 
. Select *Create user database*.
. On the Create user database page, under Database information, provide the following: 
.. *Database name*: Enter name for the database. 
.. *Collation*: Select the collation for the database. The default collation SQL_Latin1_General_CP1_CI_AS" on Microsoft SQL server is selected. 
. Under File settings, provide the following: 
.. *File settings mode*: Select *Advanced create*. 
.. *File names & path*:
... *Data file*: Select a drive letter and enter the data file name.
... *Log file*: Select a drive letter and enter the log file name. 
.. *File sizes*: Enter the data size and log size for the database.
. Click *Create*.
--

To check the job's progress, go to the *Job monitoring* tab. 