---
sidebar: sidebar
permalink: detect-host.html
keywords: detect, detect server, discover host, detect a database host, database host 
summary: Detect a Microsoft SQL server in Workload Factory for Databases. 
---
= Detect a Microsoft SQL server in Workload Factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Detect a Microsoft SQL server in Workload Factory Databases. 

== About this task
The first step to managing Microsoft SQL servers, or hosts, in Workload Factory for Databases is detecting an unidentifiable host.  

In Databases, hosts are categorized as follows: 

* _Unidentifiable hosts_: undetected hosts that have been automatically discovered by Workload Factory
* _Unmanaged hosts_: detected hosts that are not managed by Workload Factory
* _Managed hosts_: detected hosts that are managed by Workload Factory

This task is for detecting an _unidentifiable host_.

== Before you begin
The requirements for detecting an unidentifiable host are as follows: 

* You must have AWS account credentials (Link to credentials)
* The storage type for the host must be one of the following: 
** FSx for ONTAP
** AWS Elastic Block Storage (EBS) 
** AWS Elastic File Storage (EFS) 
** FSx for Windows File Servers (FSx for Windows)
** Cloud Volumes ONTAP 
* EC2 instances must have a role/instance profile that allows SSM connection for detection to work. 
+
When a Microsoft SQL host is detected, the existing environment isn't modified. Detection happens through AWS Systems Manager Session Manager (SSM). Without the right IAM instance profile, detection will fail. link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html[Learn more about SSM troubleshooting^].

.Steps
. Log in to Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Select the *Unidentified hosts* tab. 
. Click *Detect host* for the unidentified host you want to detect.
+
Workload Factory tries to validate your Microsoft SQL credentials or FSx for ONTAP credentials. 
+
If either of these credentials isn't available, Workload Factory tries to install the `aws.tools.SimpleSystemsManagement` module in PowerShell.
. The *Detect host* dialog appears. In the dialog, provide the Microsoft SQL Server user name and password. 
. Click *Detect*.
+
Detected host information appears. The host is now listed in the *Unmanaged hosts* tab. 
. Click *Done*. 

To check the job's progress, go to the *Job monitoring* tab. 

== What's next
When the storage type for the host is FSx for ONTAP, you have the option to link:manage-hosts.adoc[manage the host via Workload Factory]. 
