---
sidebar: sidebar
permalink: detect-host.html
keywords: detest, discover host, detect a database host, database host 
summary: Detect a database host in Workload Factory Databases. 
---
= Detect a host
:icons: font
:imagesdir: ./media/

[.lead]
Detect a database host in Workload Factory Databases. 

== About this task
When the requirements are met, hosts are automatically discovered in Workload Factory. You can also manually discover a host. 

Hosts cannot be detected without AWS account credentials.

Hosts are categorized as follows: 

* _Unidentifiable hosts_: hosts that are not detected
* _Unmanaged hosts_: detected hosts that are not managed by Workload Factory
* _Managed hosts_: detected hosts that are managed by Workload Factory

This task is for detecting an unidentifiable host. 

=== MS-SQL host detection 
When a Microsoft SQL host is detected, the existing environment isn't modified. Detection happens through Amazon's SSM service. So, the EC2 instances should have role/instance profile that allows AWS Systems Manager Session Manager (SSM) connection for detection to work. link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html[Learn more about SSM troubleshooting^].


== Before you begin
You need the following to complete this task: 

* AWS credentials (Link to credentials)
* Anything else? 

.Steps
. In Databases, select the *Inventory* tab. 
. Click *Detect host* for the unidentified host you want to detect.
+
Workload Factory tries to validate your SQL credentials or FSx for ONTAP credentials. 
+
If either of these credentials isn't available on system, Workload Factory tries to install AWS.Tools.SimpleSystemsManagement module in PowerShell.

. A dialog appears. In the dialog, provide the Microsoft SQL Server user name and password, and the FSx for ONTAP system user name and password. 
. Click *Detect*.
. Detected host information appears if detection is successful. The host is now listed in the *Unmanaged hosts* tab. 
.. The storage types for hosts can be FSx for ONTAP, AWS EBS, AWS EFS, FSx for Windows, and Cloud Volumes ONTAP. After detection when the storage type isn't FSx for ONTAP, the hosts are listed in the *Unmanaged hosts* tab. 
.. When the storage type is FSx for ONTAP, you have the option to manage the host via Workload Factory. 
. Click *Done*. 

If detection fails, …?
