---
sidebar: sidebar
permalink: hosts-overview.html
keywords: hosts overview, about hosts
summary: This is the overview of hosts. 
---
= About hosts
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory Databases helps you discover, deploy, protect, and manage Microsoft SQL server environments using Amazon FSx for NetApp ONTAP as the storage backend. FSx for ONTAP provides the foundation for your database management like host discovery and deployment, job monitoring, and pre-deployment cost assessment, and a full suite of protection options, such as link:https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html[AWS Backup^], FSx for ONTAP snapshots, and link:https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-full-database-backup-sql-server?view=sql-server-ver16[Native SQL server backup^]. 

== Discover and deploy hosts
Workload Factory Databases detects and deploys database hosts. When AWS credentials are associated in Workload Factory, Databases allows automated discovery of Microsoft SQL servers beginning with SQL server 2016 with the following storage types: 

* FSx for ONTAP
* FSx for Windows File Servers
* FSx for Elastic Block Storage (EBS)
//* FSx for Elastic File Storage (EFS)

In Databases, deploying a Microsoft SQL server is possible with the following tools:

* Workload Factory user interface
* Codebox: includes the following tools: 
** AWS CloudFormation template
** AWS CLI
** REST API

These deployment tools help you optimize deployment efforts with automation. Microsoft, AWS, and NetApp best practices are integrated in the deployment options to offer optimal configuration. 

In the Workload Factory Databases user interface, dashboard, inventory, and job monitoring screens provide helpful information about your hosts with access to use the detect and deploy host features. The inventory view provides a view of all database hosts. On a granular level, each host's inventory provides host details, status, protection, resource utilization, such as CPU usage, memory usage, and storage usage, and host topology. 

Hosts that are listed in Workload Factory Databases inventory are named as follows: 

* _Unidentifiable hosts_: hosts that are not detected
* _Unmanaged hosts_: detected hosts that are not managed by Workload Factory
* _Managed hosts_: detected hosts that are managed by Workload Factory

Learn how to detect and deploy hosts. (Add links) 
