---
sidebar: sidebar
permalink: learn-databases.html
keywords: Databases
summary: Databases is an end-to-end database deployment and maintenance service with built-in best practices for optimization, automatic thin cloning, application aware backup, disaster recovery, and monitoring and resolution capabilities. 
---
= Learn about Workload Factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for Databases is an end-to-end database deployment and maintenance service with built-in best practices for optimization, automatic thin cloning, and monitoring and resolution capabilities. 

=== What is Workload Factory? 
Workload Factory is a NetApp co-pilot for automated and optimized FSx for ONTAP workloads. 

It's a free, Software as a service (SaaS) workload-oriented control plane and automation platform for workloads on FSx for ONTAP. It helps you get started and apply best practices, reduce costs, and get the most out of FSx ONTAP. 

Workload Factory focuses on enterprise workload operations instead of storage operations. It helps you focus on desired workload outcomes rather than the operations required to meet these outcomes. 

== What is Workload Factory for Databases?
Workload Factory for Databases helps you discover, deploy, protect, and manage Microsoft SQL server environments using Amazon FSx for NetApp ONTAP (FSx for ONTAP) as the storage backend. FSx for ONTAP provides the foundation for your database management like host discovery and deployment, job monitoring, and pre-deployment cost assessment, and a full suite of protection options.

Workload Factory for Databases detects, assesses, plans, provisions, and moves Microsoft SQL Server data to Amazon FSx for NetApp ONTAP (FSx for ONTAP) deployments optimized to meet your desired performance and costs while adhering to industry best practices. Throughout the life cycle, Workload Factory delivers continuous optimization and management for databases on FSx for ONTAP. 

== Workload Factory benefits for self-managed databases
Workload Factory offers the following beneficial best practices and automation for self-managed databases. 

=== Best practices

* Integrated knowledge from AWS Cloud, Microsoft Windows and SQL servers, and NetApp ONTAP for SQL server deployments on EC2 instances.
* Total cost of ownership optimized deployment  
* End-to-end deployment automation that follows AWS, Microsoft and ONTAP best practices 
* “Quick create” deployment mode helps you avoid potential pitfalls with manual configuration. 

=== Automation with Workload Factory Codebox
Workload Factory introduces built-in automation with the _Codebox_. The Codebox offers the following automation benefits: 

* *Code snippet generation*: Infrastructure-as-Code (IaC) snippets are generated during resource creation, allowing seamless integration with existing orchestration workflows. 
* *Infrastructure-as-code co-pilot*: the Codebox is an IaC co-pilot that helps developers and DevOps generate code to execute any operation supported by Workload Factory.  
* *Code viewer and automation catalog*: the Codebox provides a code viewer for quick analysis of automation and an automation catalog for quick future re-use. 

=== Workload Factory for Databases features
Workload Factory for Databases offers the following features: 

* AWS resource provisioning
* Storage provisioning
* FCI and stand-alone architectures
* Database cloning for testing, development, QA, and training
* A savings calculator to compare storage costs between AWS Elastic Block Storage (EBS) and Amazon FSx for NetApp ONTAP
* Networking
* OS configurations
* AWS, Microsoft, and NetApp best practices integration
* Automated orchestration 
* _Quick create_ and _Advanced create_ deployment options 

* *Detection*: Automatically detect Microsoft SQL Servers on FSx for ONTAP, FSx for Windows File Servers, and Elastic Block Storage deployed from your AWS account. The Databases Inventory serves as a launching point for exploring costs savings opportunities for servers in other AWS storage systems or a management tool for FSx for ONTAP based servers and instances. 
* *Assessment and Planning*: assess potential cost savings with Workload Factory’s storage calculator that estimates and details storage, compute, SQL licensing, snapshot, and clone itemized costs for existing Microsoft SQL Server deployments with FSxW or EBS compared with FSx for ONTAP. 
* *Provisioning*: 	
** *Simple, fast deployments* - Simplify and streamline your provisioning experience by selecting answers to specification questions and eliminating the time typically required to investigate how to provision and configure your Microsoft SQL Server on AWS. 
** *Automated orchestration* - Available via the Workload Factory user interface with Quick and Advanced Create deployment modes, Workload Factory's Chatbot, and API with AWS CloudFormation. 
** *Built-in best practices* 
** *Built-in AWS resource selection* 
** *Cost estimation* - Get a cost estimate for each complete deployment in the user interface. The estimates provided are for general comparisons only. The estimates are based on on-demand costs and actual costs may be lower. 
** *Reusable automation templates* - Create, re-use, and customize CloudFormation templates from the Workload Factory Codebox for future Microsoft SQL Server deployments in multiple environments. 
* *Operations*:
** *Sandbox creation* - Create an on-demand, isolated database environment that can be used for testing, integration, diagnostics, and training, without affecting production data. 
** *Database creation* - Create a user database for your existing Microsoft SQL Server with Quick or Advanced create modes to configure your database collation, file names, and sizes. Storage configuration is included. 
** *Job Monitoring* - Monitor and track database job execution progress and diagnose and troubleshoot issues in case any failure occurs.  

== Benefits of Amazon FSx for ONTAP for self-managed databases

* *Durability, availability, and reliability*: FSx for ONTAP offers multiple features that enhance the durability and availability of self-managed databases hosted on FSx for ONTAP, such as high availability supporting single and multiple Availability Zones deployments, application-aware snapshots, improved disaster recovery using replication, and efficient backup. 
* *Performance and scalability*: FSx for ONTAP offers performance optimization with high throughput, low latency, and high-speed network connections, and scalability with multiple file systems for scaling aggregate performance required for a workload.
* *Data management and efficiency*: FSx for ONTAP offers multiple features that enhance data management and efficiency, such as space efficient thin clones, thin provisioning, compression and deduplication, and tiering to the capacity pool. 

For more details about FSx for ONTAP features, refer to (Learn about FSx for ONTAP for Workload Factory). 

=== Operational modes in Workload Factory
Three different operational modes - _Basic_, _Read_, and _Automate_ - offer flexible options for deployment inside and outside of Workload Factory. Gain immediate value at zero-trust in _Basic_ mode with code snippets for use outside Workload Factory. Get incremental value with incremental trust in _Read_ and _Automate_ modes. 

Learn more about link:https://review.docs.netapp.com/us-en/workload-setup-admin_first-draft/operational-modes.html[operational modes in Workload Factory^].

== Deployment details

=== Supported configurations
Workload Factory for Microsoft SQL Server supports both high availability (Always on Failover Cluster Instances) and single instance deployments according to AWS, NetApp ONTAP and SQL Server best practices. 

[cols="2a,2a,2a,2a" options="header"]
|===
// header row
| SQL Server Version
| Windows Server 2016
| Windows Server 2019
| Windows Server 2022

// first body row
| SQL Server 2016
| Yes
| Yes
| Unsupported

// second body row
| SQL Server 2019
| Yes
| Yes
| Unsupported

// third body row
| SQL Server 2022
| Yes
| Yes
| Unsupported

//table end
|===

=== Deployment architectures
(need input)

=== Integrated AWS services
Databases includes the following integrated AWS services: 

* CloudFormation
* Simple Notification Service 
* CloudWatch
* Systems Manager
* Secrets Manager 

=== Supported regions
Databases is supported in all commercial regions where FSx for ONTAP is supported. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

The following AWS regions aren't supported: 

* China regions
* GovCloud (US) regions
* Secret Cloud
* Top Secret Cloud

== Getting help
