---
sidebar: sidebar
permalink: learn-databases.html
keywords: Databases
summary: "NetApp Workload Factory for Databases is an end-to-end database deployment and maintenance service with built-in best practices for optimization, automatic thin cloning, and monitoring and resolution capabilities." 
---
= Learn about NetApp Workload Factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Workload Factory for Databases is an end-to-end database deployment and maintenance service with built-in best practices for optimization, automatic thin cloning, and monitoring and resolution capabilities.

== What is NetApp Workload Factory for Databases?
NetApp Workload Factory for Databases detects, assesses, plans, provisions, and moves Microsoft SQL Server data to Amazon FSx for NetApp ONTAP (FSx for ONTAP) deployments optimized to meet your performance and cost expectations while adhering to industry best practices. Throughout the life cycle, NetApp Workload Factory for Databases delivers continuous optimization and management for databases on FSx for ONTAP.

For more information about Workload Factory, refer to the link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html[Workload Factory overview^].

== Workload Factory benefits for self-managed databases
Workload Factory offers the following beneficial best practices and automation for self-managed databases.

=== Best practices

* Integrated knowledge from AWS Cloud, Microsoft Windows and SQL servers, and NetApp ONTAP for SQL server deployments on EC2 instances.
* Total cost of ownership optimized deployment.  
* End-to-end deployment automation that follows AWS, Microsoft and ONTAP best practices. 
* _Quick create_ deployment mode helps you avoid potential pitfalls with manual configuration. 

=== Automation with Workload Factory Codebox
Workload Factory introduces built-in automation with the _Codebox_. The Codebox offers the following automation benefits: 

* *Code snippet generation*: Infrastructure-as-Code (IaC) snippets are generated during resource creation, allowing seamless integration with existing orchestration workflows.
* *Infrastructure-as-code co-pilot*: the Codebox is an Infrastructure-as-code (IaC) co-pilot that helps developers and DevOps generate code to execute any operation supported by Workload Factory.
* *Code viewer and automation catalog*: the Codebox provides a code viewer for quick analysis of automation and an automation catalog for quick future re-use.

=== Workload Factory for Databases features
Workload Factory for Databases offers the following features:

* *Simple, fast deployments*: simplify and streamline your provisioning experience by selecting answers to specification questions and eliminating the time typically required to investigate how to provision and configure your Microsoft SQL Server on AWS.
* *Automated orchestration*: available via the Workload Factory console with _Quick_ and _Advanced_ create deployment modes, the Chatbot, and AWS CloudFormation via the Codebox.
* *Built-in features*: utilize NetApp, Microsoft, and Amazon best practices and AWS resource selections built in to deployment configuration.
* *Cost estimation*: assess potential cost savings with the Savings calculator that estimates and details storage, compute, SQL licensing, snapshot, and clone itemized costs for existing Microsoft SQL Server deployments with Elastic Block Store and FSx for Windows File Server compared with FSx for ONTAP.
* *Reusable automation templates*: create, re-use, and customize CloudFormation templates from the Workload Factory Codebox for future Microsoft SQL Server deployments in multiple environments.
* *AWS resource discovery and provisioning*: automatically detect Microsoft SQL Servers on FSx for ONTAP, FSx for Windows File Servers, and Elastic Block Store deployed from your AWS account. The Databases Inventory serves as a launching point for exploring costs savings opportunities for servers in other AWS storage systems or a management tool for FSx for ONTAP based servers and instances.
* *Sandbox creation*: create an on-demand, isolated database environment that can be used for testing, integration, diagnostics, and training, without affecting production data. 
* *Database creation*: create a user database for your existing Microsoft SQL Servers with _Quick_ or _Advanced_ create modes to configure your database collation, file names, and sizes. Storage configuration is included. 
* *Job Monitoring*: monitor and track database job execution progress and diagnose and troubleshoot issues in case any failure occurs.
* *Continuous optimization*: continuously scans your Microsoft SQL Server estate offline, providing you with a comprehensive report of insights, opportunities, and recommendations to help you achieve operational excellence.

== Benefits of Amazon FSx for ONTAP for self-managed databases

* *Durability, availability, and reliability*: FSx for ONTAP offers multiple features that enhance the durability and availability of self-managed databases hosted on FSx for ONTAP, such as high availability supporting Single and Multiple Availability Zones deployments, application-aware snapshots, improved disaster recovery using replication, and efficient backup. 
* *Performance and scalability*: FSx for ONTAP offers performance optimization with high throughput, low latency, high-speed network connections, and scalability with multiple file systems for scaling aggregate performance required for a workload.
* *Data management and efficiency*: FSx for ONTAP offers multiple features that enhance data management and efficiency, such as space efficient thin clones, thin provisioning, compression and deduplication, and tiering infrequently accessed data to the capacity pool. 

link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html[Learn about FSx for ONTAP for Workload Factory^]. 

=== Operational modes in Workload Factory
Three different operational modes - _basic_, _read-only_ and _read/write_ - offer flexible options for deployment inside and outside of Workload Factory. Gain immediate value at zero-trust in _basic_ mode with code snippets for use outside Workload Factory. Get incremental value with incremental trust in _read-only_ and _read/write_ modes. 

Learn more about link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html[operational modes in Workload Factory^].

//Cross-repo include for Tools section
include::https://raw.githubusercontent.com/NetAppDocs/workload-family/main/_include/learn-about-tools.adoc[]

== Supported configurations
Workload Factory supports the following database engines, versions, operating systems, and deployment models according to AWS, NetApp ONTAP, Microsoft SQL Server, Oracle, and PostgreSQL best practices.

[cols="1,1,1,1", options="header"]
|===
| Engine                | Version         | Operating System      | Deployment Model

| Microsoft SQL Server  | SQL Server 2016 | Windows Server 2016   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2019 | Windows Server 2016   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2022 | Windows Server 2016   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2016 | Windows Server 2019   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2019 | Windows Server 2019   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2022 | Windows Server 2019   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2016 | Windows Server 2022   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2019 | Windows Server 2022   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2022 | Windows Server 2022   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2017 | Any                   | FCI, Single instance
| Microsoft SQL Server  | SQL Server 2016, 2017,2019, 2022  | Any | FCI, Single instance

| Oracle                | 19c             | RHEL, SuSe Linux      | Standalone (Single/Multi tenant)
| Oracle                | 21c             | RHEL, SuSe Linux      | Standalone (Single/Multi tenant)
| Oracle                | 19c             | RHEL, SuSe Linux      | Standalone (Single/Multi tenant)
| Oracle                | 21c             | RHEL, SuSe Linux      | Standalone (Single/Multi tenant)
| Oracle                | 19c             | RHEL, SuSe Linux      | Standalone with ASM (Single/Multi tenant)
| Oracle                | 21c             | RHEL, SuSe Linux      | Standalone with ASM (Single/Multi tenant)

| PostgreSQL            | PostgreSQL 15   | Amazon Linux 2023 AMI | HA, Standalone instance
| PostgreSQL            | PostgreSQL 16   | Amazon Linux 2023 AMI | HA, Standalone instance
|===

== Integrated AWS services
Databases includes the following integrated AWS services: 

* CloudFormation
* Simple Notification Service 
* CloudWatch
* Systems Manager
* Secrets Manager 

== Regions
Databases is supported in all commercial regions where FSx for ONTAP is supported. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

The following AWS regions aren't supported: 

* China regions
* GovCloud (US) regions
* Secret Cloud
* Top Secret Cloud

== Getting help
Amazon FSx for NetApp ONTAP is an AWS first-party solution. For questions or technical support issues associated with your FSx for ONTAP file system, infrastructure, or any solution using this service, use the Support Center in your AWS Management Console to open a support case with AWS. Select the “FSx for ONTAP” service and appropriate category. Provide the remaining information required to create your AWS support case.

For general questions about Workload Factory or Workload Factory applications and services, refer to link:get-help.html[Get help for NetApp Workload Factory for Databases].