---
sidebar: sidebar
permalink: manage-instance.html
keywords: Microsoft SQL Server instance, PostgreSQL server instance, Oracle host instance, manage host, view host, database host, database instance, manage, unregister
summary: "Manage Microsoft SQL Server instances in BlueXP workload factory for Databases." 
---
= Instance management in workload factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Managing registered host instances in workload factory includes deploying resources for your instances like creating databases and database clones, and monitoring instance and database status, resource utilization, protection, and storage performance in workload factory for Databases. Additionally, you can analyze the well-architected status of your database configurations and implement configuration best practices to improve performance and lower operational costs. 

Management tasks include:

* link:create-database.html[Creating a database]
* link:create-sandbox-clone.html[Creating a database clone (sandbox)]
* link:view-databases.html[Viewing databases]
* link:monitory-databases.html[Monitoring]
* link:optimize-configurations.html[Implementing well-architected database configurations]


