---
sidebar: sidebar
permalink: manage-hosts.html
keywords: 
summary: Manage a server within Workload Factory Databases. 
---
= Manage hosts
:icons: font
:imagesdir: ./media/

[.lead]
Manage an unmanaged server with FSx for ONTAP storage in Workload Factory databases. 

== Manage a host
The second step to managing Microsoft SQL servers, or hosts, in Workload Factory Databases is managing an unmanaged host.  

In Databases, hosts are categorized as follows: 

* _Unidentifiable hosts_: undetected hosts that have been automatically discovered by Workload Factory
* _Unmanaged hosts_: detected hosts that are not managed by Workload Factory
* _Managed hosts_: detected hosts that are managed by Workload Factory

This task is for managing an _unmanaged host_.

== Before you begin
The server you want to manage must be an unmanaged Microsoft SQL server with FSx for ONTAP storage in Workload Factory.   

.Steps
. Log in to Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Select the *Unmanaged hosts* tab. 
. Click on the three dots menu of the unmanaged host you want to manage in Workload Factory. 
. Select *Manage host*. 
Unmanaged hosts that have storage types other than FSx for ONTAP cannot be managed in Workload Factory. Select *Explore savings* if you want to compare your storage type to FSx for ONTAP. 

== What's next
Now you can view host details, view the list of databases in the host, and create a user database from the *Managed hosts* tab. (Provide links to each topic)