---
sidebar: sidebar
permalink: manage-hosts.html
keywords: manage host
summary: Manage Microsoft SQL server instances in Databases. 
---
= Manage Microsoft SQL server instances
:icons: font
:imagesdir: ./media/

[.lead]
Manage Microsoft SQL server instances in Databases. 

Databases can only manage Microsoft SQL server instances with FSx for ONTAP file system storage. 

== Host management 
Host management includes the following tasks: 

* Manage a host instance
* View a managed instance
* View databases
* Unmanage a host instance
* Remove a managed host

To complete any of these tasks, you must link:detect-host.html[detect one or more host instances^]. 

=== Manage a host instance 
Manage a detected or unmanaged instance for a host.

=== Before you begin
You must have a detected instance in the host that is available for management. 

.Steps
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click *Manage* in the row of the host to manage. 
. Select one or more instances to manage. 
. Click *Manage*. 

The operation fails when the Microsoft SQL server is missing certain PowerShell modules and management scripts. Workload Factory triggers a repair job to install missing modules and scripts which you can view in the Job monitoring tab. When the job completes, retry to manage the host.

=== View a managed instance
You can view a managed instance by following these steps.

.Steps
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click the dropdown arrow to expand the row of the host to view its managed instances. 
+
The host expands and the host instances appear. 
. Click the three dots menu of the instance to view.
. Select *View instance*. 

The overview of the instance appears in the Inventory tab. 

=== View databases 
You can view the databases managed by the managed instance by following these steps. 

.Steps
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click the dropdown arrow to expand the row of the host to view its managed instances.
+
The host expands and the host instances appear.  
. Click the three dots menu of the instance that manages the databases to view.
. Select *View databases*. 

=== Unmanage a host instance
Unmanage a host instance by following these steps.

.Steps
. Log in to the Workload Factory console.
. In the Databases tile, click *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click the dropdown arrow to expand the row of the host instance to unmanage. 
+
The host expands and the host instances appear. 
. Click the three dots menu of the instance to unmanage. 
. Select *Unmanage*. 

The host instance is now unmanaged. 

=== Remove a managed host
??


