---
sidebar: sidebar
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs
summary: Track database jobs and monitor databases within Workload Factory for Databases.  
---
= Monitor databases
:icons: font
:imagesdir: ./media/

[.lead]
Track database jobs and monitor databases with Workload Factory for Databases. 

.About this task 
Databases provides job monitoring so you can track job progress, and diagnose and troubleshoot in case any failure occurs. In addition, filters by type and status, the search function, and the option to download the jobs table help with database jobs navigation and reporting.

Job monitoring supports up to three levels of monitoring depending on the job. For example, for new database and sandbox clone creation, job monitoring tracks parent jobs and sub-jobs.  

Job monitoring levels::: 

* Level 1 (parent job): Tracks the host deployment job.
* Level 2 (sub-job): Tracks the sub-jobs related to the host deployment parent job. 
* Level 3 (task): Lists the sequence of actions taken on each resource.

Job status:::
The job monitoring feature tracks _in progress_, _completed_, and _failed_ jobs daily, weekly, bi-weekly, and monthly. 

Job events retention:::
Job monitoring events are retained in the user interface for 30 days. 

== Monitor jobs

.Steps
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].
. In the Databases tile, select *Go to Databases Inventory*.
. In Databases, select the *Job monitoring* tab. 
. In the Job monitoring tab, use the filters or search to narrow job results. You can also download a jobs report. 
. Click the three dots menu of the job and click *Go to CloudFormation* to view the job log in the AWS CloudFormation console.  

