---
sidebar: sidebar
permalink: optimize-overview.html
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance
summary: "Workload Factory for Databases analyzes Microsoft SQL Server and Oracle configurations regularly to determine if any there are any issues."   
---
= Configuration analysis for database environments in Workload Factory 
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for Databases analyzes database configurations regularly to determine if there are any issues with Microsoft SQL Server and Oracle deployments on Amazon FSx for NetApp ONTAP storage. When issues are found, Workload Factory shows you what the issues are and explains what needs to change to ensure your database configurations achieve peak performance, cost efficiency, and compliance with best practices.

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations
* Right-sizing recommendations
* Proactive observability
* Insights to action
* AWS Well-Architected Framework advisor

== Components of the configuration analysis
The configuration analysis includes the following components:

Well-architected status::
The well-architected status refers to the overall health of your database configurations; configurations are categorized as "optimized", "not optimized", or "over-provisioned". The well-architected status of a configuration is referenced from within a Microsoft SQL Server instance or Oracle database in the Workload Factory console.

Well-architected score:: 

The score includes all currently analyzed configurations and appears as a percentage. A 25% score means that 25% of your database deployments are well-architected. The well-architected score is referenced from the *Well-architected* screen and from within a Microsoft SQL Server instance or Oracle database in the Workload Factory console. 

Configuration categories::
The configurations are organized into the following categories: storage, compute, application, resiliency, and cloning. Each category includes specific configuration assessments that are analyzed regularly. Configuration categories are referenced from the *Well-architected* screen and from within a Microsoft SQL Server instance or Oracle database in the Workload Factory console.

== Analysis scope 
The scope of optimization is different depending on which component is being assessed. For example, storage optimization occurs at the SQL instance level whereas compute optimization occurs at the host level. 

== Analysis requirements
For a complete database environment analysis, resources must be registered and online.

link:register-instance.html[Learn how to register resources.]

.What's next

link:optimize-configurations.html[Implement well-architected database configurations]


