---
sidebar: sidebar
permalink: optimize-overview.html
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance
summary: "Workload Factory for Databases analyzes Microsoft SQL Server and Oracle configurations regularly to determine if any there are any issues."   
---
= Configuration analysis for database environments in Workload Factory 
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for Databases analyzes database configurations regularly to determine if there are any issues with Microsoft SQL Server and Oracle deployments on Amazon FSx for NetApp ONTAP storage. When issues are found, Workload Factory shows you what the issues are and explains what needs to change to ensure your database configurations achieve peak performance, cost efficiency, and compliance with best practices.

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations
* Right-sizing recommendations
* Proactive observability
* Insights to action
* AWS Well-Architected Framework advisor

== How it works 

Workload Factory analyzes Microsoft SQL Server and Oracle deployments daily. The analysis provides well-architected status, insights, and recommendations. You can automatically fix configuration issues to meet best practices and operate efficiently.

After the daily analysis completes, configurations appear as "optimized" or "not optimized" in the Well-architected dashboard for the deployment. You'll find the total optimization score, configuration issues by category, and a list of configuration issues and recommendations. You can review the recommendations for configuration issues. Some issues can be fixed automatically by Workload Factory, while others require manual intervention. In this case, Workload Factory provides detailed instructions to help you implement the recommended changes.

You can dismiss the analysis of configurations that do not apply to your environments. This avoids unnecessary alerts and inaccurate optimization results. When you dismiss a specific configuration analysis, Workload Factory does not include the configuration in the total optimization score.

== Why it matters

Workload Factory applies best practices to large storage or database environments by combining ongoing assessment with recommendation insights and remediation. Automated fixes reduce human error, ensure uniform management, and maintain performance and reliability. Fixes applied in the Workload Factory console reduce human error and ensure uniform management. Automation ensures configurations are applied correctly and maintained, preserving performance and reliability across your workload infrastructures.

== Analysis requirements
For a complete database environment analysis, you must do the following: resources must be registered and online.

* link:register-instance.html[Register your resources] and make sure they are online.

* Associate a link. Link connectivity lets Workload Factory analyze all database deployment configurations like storage layout and resiliency.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. 
* Grant _view, planning, and analysis_ permissions in your AWS account. 
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[Learn how to grant permissions to an AWS account^]

.What's next

link:optimize-configurations.html[Implement well-architected database configurations]


