---
sidebar: sidebar
permalink: optimize-storage.html
keywords: optimize, storage, storage assessment, scan, optimization, Microsoft SQL Server, host, FSx for ONTAP
summary: Databases scans storage configurations of Microsoft SQL Servers providing insights and recommendations to help you achieve operational excellence. 
---
= Optimize storage for Microsoft SQL Server host instances
:icons: font
:imagesdir: ./media/

[.lead]
BlueXP workload factory for Databases continuously scans and assesses the storage settings and configurations of your Microsoft SQL Server deployments on Amazon FSx for NetAPP ONTAP. 

.About this task
The storage assessment runs automatically and continuously once every 2 days for Microsoft SQL Server host instances with FSx for ONTAP storage managed in workload factory. If needed, you can run an on-demand assessment.

Workload factory provides detailed recommendations to optimize storage settings and configurations based on best practices for FSx for ONTAP storage. 

What is scanned::
Workload factory assesses the optimization status of the following settings and configurations for Microsoft SQL Server host instances with FSx for ONTAP storage:  

* *Storage sizing*: includes storage tier, file system headroom, log drive size, TempDB drive size,  
* *Storage layout*: includes user data files placement, transaction log files placement, and TempDB placement
* *Storage configuration*: includes capacity management, thin provisioning, tiering policy, snapshots, and Multi-path I/O status, policy, and sessions, and more.  
* *Compute*: includes rightsizing, operating system patches 

Where scans are reported::
The storage assessment is reported as a job-based event in *Job monitoring*. The job includes a detailed description of when the assessment was performed, what was scanned, and the findings.

.Before you begin
* You must have credentials with read/automate permissions. - Which permissions are required, Aviram? 
* To assess the storage of a Microsoft SQL Server host instance, the host must be managed by workload factory and the storage type must be FSx for ONTAP. 
* Make sure you review each recommendation carefully before selecting to optimize a setting or configuration. 

.Steps
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].
. In the Databases tile, select *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click the dropdown arrow to expand the row of the host to view its managed instances. 
+
The host expands and the host instances appear. 
. Select the three dots menu of the instance to scan and then select *Optimize*. 
. On the Optimize instance page for the host, review the findings from the storage assessment. 
+
Filters are available to sort by categories, sub categories, status, severity, and tags. 
+ 
If needed, you can download a report of the findings by selecting *Export PDF*.  
. Select the dropdown arrow to view the recommendation for any configuration. Make sure you review the recommendation carefully. 
+ 
The recommendation explains what will happen if you choose to optimize. Some remediation jobs cause host instance downtimes or service interruptions.
. Select to *Optimize* unoptimized configurations. 
   
