---
sidebar: sidebar
permalink: optimize-storage.html
keywords: optimize, storage, storage assessment, scan, optimization, Microsoft SQL Server, host, FSx for ONTAP
summary: Databases scans storage configurations of Microsoft SQL Servers providing insights and recommendations to help you achieve operational excellence. 
---
= Optimize storage for Microsoft SQL Server host instances
:icons: font
:imagesdir: ./media/

[.lead]
BlueXP workload factory for Databases continuously scans and assesses the storage settings and configurations of your Microsoft SQL Server host instances offline, providing you with a comprehensive report of insights, opportunities, and recommendations to help you achieve operational excellence. 

.About this task
The storage assessment runs automatically and continuously once every 2 days for Microsoft SQL Server host instances with FSx for ONTAP storage managed in workload factory. If needed, you can run an on-demand assessment.

The following assessment findings are provided for scanned host instances in the user interface: 

* Total optimization score
* Optimization percentages per category
** Storage
** Resiliency
** Compute
** Cloning
** Application

What is scanned::
Workload factory fetches the status of the following settings and configurations for Microsoft SQL Server host instances with FSx for ONTAP storage:  

* *Storage sizing*: Over-provisioned, Under-provisioned, Optimized
* *Storage layout*: Optimized, Not optimized (Warning), and Not optimized (Action required)
* *Storage configuration*: Optimized, Not optimized (Warning), and Not optimized (Action required)
* *Compute*: Over-provisioned, Under-provisioned, Optimized

Where scans are reported::
The storage assessment is reported as a job-based event in *Job monitoring*. The job includes a detailed description of when the assessment was performed, what was scanned, and the findings.

.Before you begin
To assess the storage of a Microsoft SQL Server host instance, the host must be managed by workload factory and the storage type must be FSx for ONTAP. 

.Steps
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^].
. In the Databases tile, select *Go to Databases Inventory*.
. In Databases, select the *Inventory* tab. 
. Click the dropdown arrow to expand the row of the host to view its managed instances. 
+
The host expands and the host instances appear. 
. Select the three dots menu of the instance to scan and then select *Optimize*. 
. On the Optimize instance page for the host, review the findings from the storage assessment. 
+
Filters are available to sort by categories, sub categories, status, severity, and tags. 
+ 
If needed, you can download a report of the findings by selecting *Export PDF*.  
. Select the dropdown arrow for any configuration to view the recommendation. 
. Select to *Optimize* unoptimized configurations. 
   
