settings:
  name: "Databases"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  

sidebar: 
  entries:
  - title: Database workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about Databases
        url: /learn-databases.html
      - title: Quick start
        url: /quick-start.html
  - title: Requirements
    entries: 
      - title: Credentials
        url: /credentials-databases.html
      - title: Permissions
        url: /permissions-databases.html
  - title: Use Databases
    entries: 
      - title: Create a database
        url: /create-database.html
      - title: Manage a database
        url: /manage-database.html  
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration-databases.html
      - title: Get help
        url: /get-help-databases.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: Workload Factory
  repo: workload-family
