settings:
  name: "Databases"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  

sidebar: 
  entries:
  - title: Database workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about Workload Factory Databases
        url: /learn-databases.html 
      - title: Quick start
        url: /quick-start-databases.html
  - title: Use Database workloads
    entries: 
    #  - title: Automate with Codebox
    #    url: automate-codebox.html
      - title: About hosts
        url: /hosts-overview.html
      - title: Create a new database host
        url: /create-database-host.html
      - title: Detect a database host
        url: /detect-host.html 
      - title: About databases
        url: /databases-overview.html
      - title: Create a database
        url: /create-database.html
  - title: Administer and monitor
    entries:
    #  - title: Manage database servers
    #    entries: 
    #  - title: Manage databases
    #    entries: 
      - title: Monitor databases
        url: /monitor-databases.html
      - title: Manage clones
        entries: 
          - title: Create a sandbox clone 
            url: create-sandbox-clone.html                  
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration-databases.html
      - title: Get help
        url: /get-help-databases.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: Workload Factory
  repo: workload-family
