jekyll: bnorberg-sidebar
settings:
  name: "Databases"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"  

sidebar: 
  entries:
  - title: Database workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about Workload Factory Databases
        url: /learn-databases.html
      - title: Requirements
        url: /requirements-databases.html  
#      - title: Quick start
#        url: /quick-start.html
  - title: Use Database workloads
    entries: 
      - title: About hosts
        url: /hosts-overview.html
      - title: Deploy a host
        url: /deploy-host.html
      - title: Detect a host
        url: /detect-host.html 
      - title: About databases
        url: /databases-overview.html
      - title: Create a database
        url: /create-database.html
  - title: Administer and monitor
    entries:
      - title: Monitor databases
        url: /monitor-databases.html 
      - title: Assess costs
        url: /assess-costs-databases.html
      - title: Automate with Codebox
        entries: 
          - title: Automation catalog
            url: /automation-catalog.html
          - title: Code viewer
            url: /code-viewer.html              
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration-databases.html
      - title: Get help
        url: /get-help-databases.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: Workload Factory
  repo: workload-family
