settings:
  name: "Database workloads" 
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes  

sidebar: 
  entries:
  - title: Database workloads docs
    url: /index.html
  - title: Release notes  
    entries:
      - title: What's new
        url: /whats-new.html
      - title: Known limitations
        url: /known-limitations.html 
  - title: Get started
    entries: 
      - title: Learn about Workload Factory for Databases
        url: /learn-databases.html 
      - title: Quick start
        url: /quick-start-databases.html 
  - title: Use Workload Factory for Database workloads
    entries: 
      - title: Explore savings
        url: /explore-savings.html
      - title: Create database resources
        entries:
          - title: Create Microsoft SQL Server    
            url: /create-database-server.html
          - title: Create PostgreSQL server
            url: /create-postgresql-server.html  
          - title: Create a database
            url: /create-database.html 
          - title: Create a sandbox clone 
            url: /create-sandbox-clone.html   
      - title: Manage resources
        entries: 
          - title: Resource management
            url: /manage-instance.html
          - title: Register resources
            url: /register-instance.html
          - title: Manage clones
            url: /manage-clones.html                  
          - title: Deregister resources
            url: /deregister-instance.html 
  - title: Protect, monitor, and optimize database resources
    entries:
      - title: Analyze error logs
        url: /analyze-error-logs.html   
      - title: Implement configuration best practices
        entries: 
          - title: Configuration analysis for Databases
            url: /optimize-overview.html
          - title: Implement well-architected database configurations   
            url: /optimize-configurations.html 
      - title: Monitor database jobs
        url: /monitor-databases.html                                              
      - title: Protect Microsoft SQL Server workloads
        url: /protect-sql-server.html         
  - title: Knowledge and support
    entries: 
      - title: Register for support
        url: /support-registration.html
      - title: Get help
        url: /get-help.html                  
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: NetApp Workload Factory
  repo: workload-family
