---
sidebar: sidebar
permalink: protect-sql-server.html
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database
summary: "Protect Microsoft SQL Server instances and databases."
---
= Protect Microsoft SQL Server workloads
:icons: font
:imagesdir: ./media/

[.lead]
Protect your Microsoft SQL Server applications data using BlueXP backup and recovery from the Workload Factory console. With this integration, you can achieve the following protection goals: back up workloads with local snapshots on local primary Amazon FSx for NetApp ONTAP (FSx for ONTAP) storage, and replicate workloads to secondary FSx for ONTAP storage. 

== About this task
Workload Factory automates discovering resources, validating prerequisites, and configuring and installing the Plug-in for Microsoft SQL Server to prepare for protecting your workloads with BlueXP backup and recovery. The plug-in is a host-side component of NetApp Software that enables you to protect your Microsoft SQL Server workloads.

NetApp Backup and Recovery leverages NetApp SnapMirror data replication technology to ensure that all the backups are fully synchronized by creating snapshot copies and transferring them to the backup locations.

For details about protection with Backup and Recovery, refer to the link:https://docs.netapp.com/us-en/console-backup-recovery/br-use-mssql-protect-overview.html[Protect Microsoft SQL workloads overview with Backup and Recovery^]. 

== Before you begin
The following requirements must be met to protect Microsoft SQL Server workloads with Backup and Recovery.

* Ensure that your environment meets link:https://docs.netapp.com/us-en/console-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements[the Backup and Recovery SQL Server requirements^].

* link:https://docs.netapp.com/us-en/console-backup-recovery/concept-start-prereq.html#in-bluexp[Complete NetApp Console requirements^] including setting up, assigning IAM roles, and installing a Console agent.

If you have organization administrator access to the NetApp account, the `backup and recovery super admin` role is automatically assigned when you <<Prepare for protection with NetApp Backup and Recovery,prepare for protection with NetApp Backup and Recovery>>.

** Set the host resolution on the Connector
+
To discover databases, you must set host resolution on the Connector. On the hosted device, add the mapping of the IP address to the hostname in the `/etc/hosts` file.

* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html[Set up licensing for BlueXP backup and recovery^]

== Prepare for protection with NetApp Backup and Recovery
Complete the preparation process to protect your Microsoft SQL Server resources with NetApp Backup and Recovery.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Databases tile, select *Go to Databases inventory*.
. From the Databases menu, select *Inventory*. 
. In the Inventory, select *Microsoft SQL Server* as the engine type.
. Locate the instance that you want to protect, and then select *Protect* from the menu.
. If prompted, provide Windows credentials with administrative access. 
+
To use NetApp Backup and Recovery for protection, SQL Server instances must be registered in Workload Factory with Windows credentials.
. If several Console agents are active and available, select the *Console agent* where you want the workload to be registered and protected.
. To prepare for data protection, Workload Factory automatically registers your SQL Server resources in Backup and Recovery, configures and installs the Plug-in for Microsoft SQL Server, and discovers resources to meet the prerequisites for protecting your SQL Server instance. Select *Start* to begin the process.
. After meeting the prerequisites, select *Redirect* to access Backup and Recovery.

.What's next
From Backup and Recovery, create a policy to protect your Microsoft SQL Server instance and databases.

link:https://docs.netapp.com/us-en/console-backup-recovery/br-use-policies-create.html[Learn how to create a policy to protect your Microsoft SQL Server instance and databases^].

For related information, refer to the link:https://docs.netapp.com/us-en/console-backup-recovery/br-use-mssql-protect-overview.html[Backup and Recovery documentation^] for managing Microsoft SQL Server workloads.