---
sidebar: sidebar
permalink: protect-sql-server.html
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database
summary: "Protect Microsoft SQL Server instances and databases."
---
= Protect Microsoft SQL Server workloads
:icons: font
:imagesdir: ./media/

[.lead]
Protect your Microsoft SQL Server applications data using BlueXP backup and recovery from the workload factory console. With this integration, you can achieve the following protection goals: back up workloads with local snapshots on local primary Amazon FSx for NetApp ONTAP (FSx for ONTAP) storage, and replicate workloads to secondary FSx for ONTAP storage. 

== About this task
Workload factory helps automate the process of discovering instance and database resources, validating prerequisites, and configuring and installing the Plug-in for Microsoft SQL Server, all of which are part of the preparation process for protecting your Microsoft SQL Server workloads with BlueXP backup and recovery. The plug-in is a host-side component of NetApp Software that enables you to protect your Microsoft SQL Server workloads.

BlueXP backup and recovery leverages NetApp SnapMirror data replication technology to ensure that all the backups are fully synchronized by creating snapshot copies and transferring them to the backup locations.

For details about protection with BlueXP backup and recovery, refer to the link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html[Protect Microsoft SQL workloads overview with BlueXP backup and recovery^]. 

== Before you begin
The following requirements must be met to protect Microsoft SQL Server workloads with BlueXP backup and recovery.

* Ensure that your environment meets link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements[the BlueXP backup and recovery SQL Server requirements^].

* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#in-bluexp[Complete BlueXP requirements^] including setting up BlueXP, IAM roles, and a BlueXP Connector.
+
The Super admin role is automatically created when you <<Prepare for protection with BlueXP backup and recovery,prepare for protection with BlueXP backup and recovery>>.
+
** Set the host resolution on the Connector
+
To discover databases, you must set host resolution on the Connector. On the hosted device, add the mapping of the IP address to the hostname in the `/etc/hosts` file.

** Install the Ubuntu 22.04 LTS operating system. This is a requirement for the BlueXP Connector.

* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html[Set up licensing for BlueXP backup and recovery^]

* In workload factory for Databases, make sure that you register instances using Windows credentials. To provide Windows credentials, go to the Instances tab from the Inventory. Identify the instance, select *Manage instances*, and then select *Instance dashboard*. From the instance dashboard, select the three-dot menu, and then select *Update Microsoft SQL Server password*. Update the password using Windows authentication. 

== Prepare for protection with BlueXP backup and recovery
Complete the preparation process to protect your Microsoft SQL Server resources with BlueXP backup and recovery.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Databases tile, select *Go to Databases inventory*.
. In Databases, select the *Inventory* tab. 
. Filter the *Engine type* to *Microsoft SQL Server*.
. Select *Protect* from the menu for the instance to protect.
. Select the *Connector* where you want the workload to be registered and protected.
. To prepare for data protection, Workload factory automatically registers your SQL Server resources in BlueXP backup and recovery, configures and installs the Plug-in for Microsoft SQL Server, and discovers resources to meet the prerequisites for protecting your SQL Server instance. Select *Start* to begin the process.
. After the prerequisites are met, select *Redirect* to get redirected to BlueXP backup and recovery.

.What's next
From BlueXP backup and recovery, create a policy to protect your Microsoft SQL Server instance and databases.

link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-policies-create.html[Learn how to create a policy to protect your Microsoft SQL Server instance and databases^].

For related information, refer to the link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html[BlueXP backup and recovery documentation^] for managing Microsoft SQL Server workloads.