---
sidebar: sidebar
permalink: refresh-clone.html
keywords: refresh clone, sync, update, database, Microsoft SQL
summary: "Refresh a sandbox clone in BlueXP workload factory for Databases."
---
= Refresh a sandbox clone in BlueXP workload factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Refresh a database clone in BlueXP workload factory for Databases so that it is equivalent to the source database at the current moment or a previous point in time. 

.About this task
Refreshing a clone updates the clone either to the source database at the current moment or to a snapshot of the source database taken at a previous point in time. Any changes made to the sandbox clone will be deleted. 

.Before you begin
A refresh is only possible when the source database is active. 

To refresh a database clone from a snapshot, the source database must have at least one snapshot for the operation.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Databases tile, select *Go to Databases inventory*. 
. In Databases, select the *Sandboxes* tab.
. In the Sandboxes tab, click the three dots menu of the sandbox clone you want to refresh.
. Select *Refresh*. 
. In the Refresh dialog, select one of the following options: 
.. *Refresh to current time*
.. *Refresh to point in time* 
+
For this option, select the database snapshot from the dropdown menu to refresh to. 
. Click *Refresh*. 
