---
sidebar: sidebar
permalink: revert-clone.html
keywords: re-baseline, revert clone, database, Microsoft SQL
summary: Revert a sandbox clone in Workload Factory for Databases.
---
= Revert a sandbox clone in Workload Factory for Databases
:icons: font
:imagesdir: ./media/

[.lead]
Revert a database clone to its original version at the time of creation. 

.About this task
When you clone a database, the clone at creation is a _baseline_ clone. The data in the cloned database is the same as the source database at the time of creation. As data in a sandbox database clone changes over time, you might want to revert the data back to the baseline when the clone was first created. This operation is called re-baselining a clone. Re-baselining a clone rather than creating a new clone saves space; however, any changes made to the sandbox clone will be deleted. 

.Steps
. Log in to the link:https://console.workloads.netapp.com[Workload Factory console^]. 
. In the Databases tile, select *Go to Databases Inventory*. 
. In Databases, select the *Sandboxes* tab.
. In the Sandboxes tab, click the three dots menu of the sandbox clone you want to revert.
. Select *Re-baseline*. 
. In the Re-baseline dialog, click *Re-baseline*. 