---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, enhancements, fixes, new features, workload factory, databases, workload factory
summary: Learn what's new with Workload Factory for Databases.
---
= What's new
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new with Databases.

== 4 August 2024

=== Savings calculator enhancements

* Cost estimate descriptions
+
You can now learn how cost estimates are calculated in the savings calculator. You'll be able to review descriptions of all calculations for your Microsoft SQL Server instances using Amazon Elastic Block Store storage as compared to using Amazon FSx for ONTAP storage.

* Support for Always On availability group 
+
Databases now provides cost savings calculations for the Always On availability group deployment type with Microsoft SQL Server using Amazon Elastic Block Store.

* Optimize SQL edition and license with FSx for ONTAP
+
The storage calculator determines whether the SQL edition and license you use with Amazon Elastic Block Store storage are optimized for your database workloads. You'll get a recommendation for the optimal SQL edition and license with FSx for ONTAP storage.  

* Multiple SQL server instances 
+
Databases now provides cost savings calculations for multiple Microsoft SQL Server instances using Amazon Elastic Block Store.

link:explore-savings.html[Explore savings with FSx for ONTAP for your database workloads.]

== 7 July 2024

=== Initial release of Workload Factory for Databases
The initial release includes the capability to explore savings with Amazon FSx for NetApp ONTAP as the storage environment for your database workloads, detect, manage, and deploy Microsoft SQL Servers, deploy and clone databases, and monitor these jobs within Workload Factory.

link:learn-databases.html[Learn about Databases].

