---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, enhancements, fixes, new features, workload factory, databases, workload factory
summary: Learn what's new with Workload Factory for Databases.
---
= What's new
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new with Databases.

== 4 August 2024

=== Savings calculator enhancements

* View cost savings calculations
+
Now you can learn how cost estimates are calculated in the savings calculator with the option to view calculations. You'll be able to view a granular comparison of your Amazon Elastic Block Store storage as compared to Amazon FSx for ONTAP storage. 

* Support for Always On availability group in savings calculator
+
Databases now provides cost savings calculations for the Always On availability group deployment type with Amazon Elastic Block Store. 

* Calculations for multiple Amazon Elastic Block Store volume types in savings calculator 
+
You can view cost savings calculations for the following volume types in Amazon Elastic Block Store when exploring savings with the calculator. 
+
** General SSD: gp3 and gp2
** Provisioned IOPS SSD: io2 and io1
** HDD: st1

link:explore-savings.html[Explore savings with FSx for ONTAP for your database workloads.]

== 7 July 2024

=== Initial release of Workload Factory for Databases
The initial release includes the capability to explore savings with Amazon FSx for NetApp ONTAP as the storage environment for your database workloads, detect, manage, and deploy Microsoft SQL Servers, deploy and clone databases, and monitor these jobs within Workload Factory.

link:learn-databases.html[Learn about Databases].

