=== Dashboard improvements

The new dashboard is streamlined and better organized to provide a clearer overview of your database resources and the key functionalities of Workload Factory on one screen; one card highlights database resources, one card provides information about the well-architected score and analysis, one card displays error analysis, two cards display monthly cost and potential savings, and one card displays information on sandboxes.

=== Well-architected analysis for Oracle

The well-architected analysis includes the following assessments and fixes for the following configurations in Oracle: 

* Storage configuration operating system using the NFS protocol: assesses and fixes configuration issues with the NFS configuration for existing Oracle database deployments.
* Storage configuration operating system using the iSCSI protocol: assesses and fixes configuration issues with the iSCSI configuration for existing Oracle database deployments.
* Storage configuration operating system using Automatic Storage Management: assesses and fixes configuration issues with the ASM configuration for existing Oracle database deployments.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html[Implement well-architected database configurations in Workload Factory]

=== Permissions changes for Workload Factory for Databases

Workload Factory for Databases provides more clarity about the permissions it requires for specific actions. When you add credentials, you'll have three permissions options to choose from instead of the previous permissions model which was _read-only_ and _read/write_. The new permissions model breaks up the permission policies as follows: 

* _*View, planning, and analysis*_: view the inventory of database resources, learn about the health of your resources, review the well-architected analysis of your database configurations, get error log analysis, and explore savings
* _*Operations and remediation*_: perform operational tasks for your database resources and fix issues for database configurations and the underlying FSx for ONTAP file system storage
* _*Database host creation*_: deploy database hosts and the underlying FSx for ONTAP file system storage according to best practices

When adding credentials, you can select one or more of these permission policies based on the level of access you want to provide to Workload Factory for Databases.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html[Workload Factory permissions reference^]

=== Well-architected menu item added

A new _Well-architected_ menu item has been added to the Databases menu. From this menu item, you can access the well-architected dashboard, which provides an overview of the well-architected score for your database deployments, along with detailed information about configuration issues and recommendations for improving your database configurations.

=== Well-architected dashboard export PDF report

You can now export a PDF report from the well-architected dashboard. This report includes an overview of your well-architected score, detailed information about configuration issues including such configurations for operating system and ONTAP. The PDF report can be useful for sharing with stakeholders or for keeping a record of your database configurations and improvements over time.

=== Edit protection for database deployments in NetApp Backup and Recovery  
Edit protection is available for resources that are protected in NetApp Backup and Recovery. From the Workload Factory console, you can select to edit protection for a protected resource and then you'll be redirected to Backup and Recovery in the NetApp Console where you can modify the protection policy or schedule.

=== Error filtering available from the Agentic AI-powered error log analyzer
You can filter and view SQL Server error logs by infrastructure-oriented categories and specific error types in the *Error Investigation* screen. This enhancement helps you quickly triage and resolve issues by narrowing down the error logs to the most relevant entries.
