=== BlueXP workload factory notification service support
The BlueXP workload factory notification service enables workload factory to send notifications to the BlueXP alerts service or to an Amazon SNS topic. Notifications sent to BlueXP alerts appear in the BlueXP alerts panel. When workload factory publishes notifications to an Amazon SNS topic, subscribers to the topic (such as people or other applications) receive the notifications at the endpoints configured for the topic (such as email or SMS messages).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[Configure BlueXP workload factory notifications]

=== Onboarding enhancement for registering host instances

Workload factory for Databases has improved its onboarding process for registering host instances running on Amazon FSx for NetApp ONTAP storage. You'll be able to select host instances in bulk for registration. Once a host instance is registered, you can create and manage database host resources within the workload factory console. 

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html[Instance management]

=== Analysis and fix for Microsoft Multipath I/O timeout setting

The well-architected status for your database host instances now includes the analysis and the fix for the Microsoft Multipath I/O (MPIO) timeout setting. When the MPIO timeout setting is set to the best practice value of 60 seconds, it ensures that the underlying FSx for ONTAP storage has connectivity and stability during file system failovers. If the MPIO setting isn't set accordingly, workload factory will provide a fix to set the MPIO timeout value to 60 seconds.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html[Implement well-architected database configurations in workload factory]

=== Enhancements to graphics in host inventory

Various resource utilization graphs like throughput and IOPS now display 7 days of data so that you can monitor performance more efficiently.