=== Custom savings for Oracle hosts on Amazon Elastic Block Store
NetApp Workload Factory for Databases lets you customize savings for Oracle hosts on Amazon Elastic Block Store (EBS). You can adjust several fields like the snapshot frequency, the number of cloned copies, and volume details to see how they affect your savings. 

link:https://docs.netapp.com/us-en/workload-factory-for-databases/explore-savings.html[Explore savings for Oracle hosts on EBS]

=== Multiple security group selection for Microsoft SQL Server and PostgreSQL host deployment
NetApp Workload Factory for Databases now allows you to select multiple security groups when deploying Microsoft SQL Server and PostgreSQL hosts. This enhancement provides greater flexibility in configuring network security for your database workloads.

* link:https://docs.netapp.com/us-en/workload-factory-for-databases/create-database-server.html[Deploy Microsoft SQL Server hosts]
* link:https://docs.netapp.com/us-en/workload-factory-for-databases/create-postgresql-server.html[Deploy PostgreSQL hosts]